// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
 static FirebaseOptions get currentPlatform {
  if (kIsWeb) {
    return web;
  }
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for android - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    case TargetPlatform.iOS:
      return ios;
    case TargetPlatform.macOS:
      return macos;
    case TargetPlatform.windows:
      return windows;
    case TargetPlatform.linux:
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    default:
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
  }
}

  

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiFWa74IOa9V7XwGQ9Pv4QGnYdc1kI7Wo',
    appId: '1:707809151646:ios:e0546198422272dc99098f',
    messagingSenderId: '707809151646',
    projectId: 'chat-app-shahd',
    storageBucket: 'chat-app-shahd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiFWa74IOa9V7XwGQ9Pv4QGnYdc1kI7Wo',
    appId: '1:707809151646:ios:e0546198422272dc99098f',
    messagingSenderId: '707809151646',
    projectId: 'chat-app-shahd',
    storageBucket: 'chat-app-shahd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJS0m-KY37IngdlXsCwCvYsIz5yRCEMhA',
    appId: '1:707809151646:web:65e660b063ff9ba899098f',
    messagingSenderId: '707809151646',
    projectId: 'chat-app-shahd',
    authDomain: 'chat-app-shahd.firebaseapp.com',
    storageBucket: 'chat-app-shahd.firebasestorage.app',
    measurementId: 'G-VSXMY50771',
  );
  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyBJS0m-KY37IngdlXsCwCvYsIz5yRCEMhA',
  appId: '1:707809151646:web:65e660b063ff9ba899098f',
  messagingSenderId: '707809151646',
  projectId: 'chat-app-shahd',
  authDomain: 'chat-app-shahd.firebaseapp.com',
  storageBucket: 'chat-app-shahd.firebasestorage.app',
  measurementId: 'G-VSXMY50771',
);
}
